### ISSUE TITLE
Database migration failure

### ISSUE THREAD

**Issue by thespad** [ddworken/hishtory#241]
Version 0.310.20240830

```
Opening DB
Connecting to DB
AutoMigrating DB tables

2024/08/31 15:06:01 /build/hishtory/backend/server/internal/database/db.go:62
[6.992ms] [rows:1] SELECT count(*) FROM information_schema.tables WHERE table_schema = CURRENT_SCHEMA() AND table_name = 'enc_history_entries' AND table_type = 'BASE TABLE'

2024/08/31 15:06:01 /build/hishtory/backend/server/internal/database/db.go:62
[0.375ms] [rows:1] SELECT CURRENT_DATABASE()

2024/08/31 15:06:01 /build/hishtory/backend/server/internal/database/db.go:62
[15.200ms] [rows:-] SELECT c.column_name, c.is_nullable = 'YES', c.udt_name, c.character_maximum_length, c.numeric_precision, c.numeric_precision_radix, c.numeric_scale, c.datetime_precision, 8 * typlen, c.column_default, pd.description, c.identity_increment FROM information_schema.columns AS c JOIN pg_type AS pgt ON c.udt_name = pgt.typname LEFT JOIN pg_catalog.pg_description as pd ON pd.objsubid = c.ordinal_position AND pd.objoid = (SELECT oid FROM pg_catalog.pg_class WHERE relname = c.table_name AND relnamespace = (SELECT oid FROM pg_catalog.pg_namespace WHERE nspname = c.table_schema)) where table_catalog = 'hishtory' AND table_schema = CURRENT_SCHEMA() AND table_name = 'enc_history_entries'

2024/08/31 15:06:01 /build/hishtory/backend/server/internal/database/db.go:62 ERROR: could not determine data type of parameter $1 (SQLSTATE 42P18)
[0.422ms] [rows:-] SELECT * FROM "enc_history_entries" LIMIT 1
panic: OpenDB: failed to create underlying DB tables: db.AutoMigrate: ERROR: could not determine data type of parameter $1 (SQLSTATE 42P18)

goroutine 1 [running]:
main.InitDB()
        /build/hishtory/backend/server/server.go:173 +0x273
main.main()
        /build/hishtory/backend/server/server.go:202 +0x9b
```

**Comment by ddworken** [comment]
Interesting, thank you for the bug report! I'm looking into this now. Given the source of the error, I think this may be a bug in the underlying gorm library (github.com/go-gorm/gorm) which I did upgrade the version of last week.

**Comment by ddworken** [comment]
Ok, it looks like the root cause here is a mismatch of versions where we were using an older version of pgx and the gorm postgres driver, but a newer version of gorm. #243 should fix this, I'm going to let it run through all the tests on GH actions and then will release it ASAP. 

I'll also follow up in a separate change to improve our test coverage to ensure we prevent this from happening again in the future.
